[versions]
androidxActivity = "1.9.0"
androidxAppcompat = "1.6.1"
androidxComposeBom = "2024.06.00"
composeCompiler = "1.5.14"
androidxCoreKtx = "1.13.1"
androidxLifecycle = "2.8.1"
androidxWork = "2.9.0"
playBilling = "6.1.0"
junit = "4.13.2"
androidxTestExt = "1.1.5"
espressoCore = "3.5.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
play-billing = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "playBilling" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version = "8.3.2" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.9.23" }
